export enum EmailLabel {
  // Native Gmail labels
  INBOX = 'INBOX',
  SPAM = 'SPAM',
  TRASH = 'TRASH',
  UNREAD = 'UNREAD',
  STARRED = 'STARRED',
  IMPORTANT = 'IMPORTANT',
  SENT = 'SENT',
  DRAFT = 'DRAFT',

  // Gmail category labels
  CATEGORY_PERSONAL = 'CATEGORY_PERSONAL',
  CATEGORY_SOCIAL = 'CATEGORY_SOCIAL',
  CATEGORY_PROMOTIONS = 'CATEGORY_PROMOTIONS',
  CATEGORY_UPDATES = 'CATEGORY_UPDATES',
  CATEGORY_FORUMS = 'CATEGORY_FORUMS',

  // Custom real estate category labels
  CATEGORY_REAL_ESTATE_ENQUIRY = 'CATEGORY_REAL_ESTATE_ENQUIRY',
  CATEGORY_REAL_ESTATE_MEETING = 'CATEGORY_REAL_ESTATE_MEETING',
  CATEGORY_REAL_ESTATE_OTHER = 'CATEGORY_REAL_ESTATE_OTHER',
}
